name: Vm updation on push
on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: yella comment yeyum run pannanum

    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          ssh-keyscan -H 34.55.186.133 >> ~/.ssh/known_hosts
          ssh -i ~/ssh_key root@34.55.186.133
          cd bms/ && git pull
          pnpm install
          pnpm run build
          pm2 restart all